version: "3.9"

services:
    mssqlserver:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
          - "1433:1433"
    dotnet-api:
        build: .
        ports:
          - "80:80"
        depends_on:
          - mssqlserver